#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│  ___           _        _                                               │"
echo "│ |   \ ___  ___| |_____ | |__  __ _ ___ ___                              │"
echo "│ | |) / _ \/ __| / / -_)| '_ \/ _\` (_-</ -_)                             │"
echo "│ |___/\___/\___|_\_\___||_.__/\__,_/__/\___|                             │"
echo "│                                                                         │"
echo "│ Docker Control Panel - Alpha                                            │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
echo -e "${NC}"

INSTALL_DIR="/opt/dockebase"
REPO_URL="https://raw.githubusercontent.com/dockebase/dockebase-alpha-images/main"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: Please run as root (sudo)${NC}"
    exit 1
fi

# Check for Docker
echo -e "${BLUE}Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed${NC}"
    echo "Install Docker: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose v2 is not installed${NC}"
    echo "Docker Compose should be included with Docker Desktop or Docker Engine"
    exit 1
fi

echo -e "${GREEN}✓ Docker and Docker Compose found${NC}"

# Check if Docker is running
if ! docker info &> /dev/null; then
    echo -e "${RED}Error: Docker daemon is not running${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Docker daemon is running${NC}"

# Create installation directory
echo -e "${BLUE}Creating installation directory...${NC}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download docker-compose.yml
echo -e "${BLUE}Downloading configuration files...${NC}"
curl -fsSL "$REPO_URL/docker-compose.yml" -o docker-compose.yml
curl -fsSL "$REPO_URL/.env.example" -o .env.example

echo -e "${GREEN}✓ Configuration files downloaded${NC}"

# Interactive configuration
echo ""
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}                    Configuration                          ${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Domain
echo -e "${BLUE}Enter your domain (e.g., panel.example.com)${NC}"
echo -e "Leave empty for localhost (no SSL):"
read -r DOMAIN
DOMAIN=${DOMAIN:-localhost}

# ACME Email (only if domain is not localhost)
ACME_EMAIL=""
if [ "$DOMAIN" != "localhost" ]; then
    echo ""
    echo -e "${BLUE}Enter your email for Let's Encrypt SSL certificates:${NC}"
    read -r ACME_EMAIL

    if [ -z "$ACME_EMAIL" ]; then
        echo -e "${RED}Error: Email is required for SSL certificates${NC}"
        exit 1
    fi
fi

# Generate auth secret
AUTH_SECRET=$(openssl rand -hex 32)

# Determine base URL
if [ "$DOMAIN" = "localhost" ]; then
    BASE_URL="http://localhost"
else
    BASE_URL="https://$DOMAIN"
fi

# Create .env file
echo -e "${BLUE}Creating configuration...${NC}"
cat > .env << EOF
# Dockebase Configuration
# Generated by install.sh

DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
BASE_URL=$BASE_URL
AUTH_SECRET=$AUTH_SECRET
EOF

echo -e "${GREEN}✓ Configuration created${NC}"

# Pull images
echo ""
echo -e "${BLUE}Pulling Docker images...${NC}"
docker compose pull

echo -e "${GREEN}✓ Images pulled${NC}"

# Start services
echo ""
echo -e "${BLUE}Starting Dockebase...${NC}"
docker compose up -d

echo -e "${GREEN}✓ Dockebase started${NC}"

# Wait for services to be ready
echo ""
echo -e "${BLUE}Waiting for services to be ready...${NC}"
sleep 5

# Check if services are running
if docker compose ps | grep -q "running"; then
    echo -e "${GREEN}✓ Services are running${NC}"
else
    echo -e "${RED}Warning: Some services may not be running properly${NC}"
    echo "Check status with: cd $INSTALL_DIR && docker compose ps"
fi

# Print success message
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}           Dockebase Installation Complete!                ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""

if [ "$DOMAIN" = "localhost" ]; then
    echo -e "Access Dockebase at: ${BLUE}http://localhost${NC}"
else
    echo -e "Access Dockebase at: ${BLUE}https://$DOMAIN${NC}"
    echo ""
    echo -e "${YELLOW}Note: SSL certificate will be automatically provisioned.${NC}"
    echo -e "${YELLOW}This may take a few minutes on first access.${NC}"
fi

echo ""
echo -e "Installation directory: ${BLUE}$INSTALL_DIR${NC}"
echo ""
echo "Useful commands:"
echo -e "  ${BLUE}cd $INSTALL_DIR${NC}"
echo -e "  ${BLUE}docker compose ps${NC}      - Check status"
echo -e "  ${BLUE}docker compose logs -f${NC} - View logs"
echo -e "  ${BLUE}docker compose down${NC}    - Stop services"
echo -e "  ${BLUE}docker compose up -d${NC}   - Start services"
echo ""
